#!/bin/bash

if [ $# -ne 1 ]
    then
        echo "Run with 'activate' argument!"
        exit
    fi

GITREVS=`git rev-list --count HEAD`
GITHASH=`git rev-parse --short HEAD`
DATE=`date +"%Y-%m-%d %H:%M"`

cat > src/lib/ams/AMSMainHeaderConfig.hpp << EOF
#define AMS_CONFIG_VERSION  "8.x"
#define AMS_VERSION         "8.${GITREVS}.${GITHASH}"
#define AMS_BUILDTIME       "${DATE}"
EOF

echo ""
echo "AMS Revision: 8.$GITREVS.$GITHASH ($DATE)"

