#!/bin/bash

if [ $# -ne 1 ]
    then
        echo "Run with 'activate' argument!"
        exit
    fi

GITREVS=`git rev-list --count HEAD`
GITHASH=`git rev-parse --short HEAD`
DATE=`date +"%Y-%m-%d %H:%M"`

sed -e "s/GITREVS/$GITREVS/g" -e "s/GITHASH/$GITHASH/g" -e "s/DATE/$DATE/g" \
    src/lib/ams/AMSMainHeader.hpp > src/lib/ams/AMSMainHeader_.hpp

mv -f src/lib/ams/AMSMainHeader_.hpp src/lib/ams/AMSMainHeader.hpp

echo ""
echo "AMS Revision: 8.$GITREVS.$GITHASH ($DATE)"

