#!/bin/bash
# =============================================================================
# AMS - Advanced Module System
# (c) 2010,2016,2017,2023 Petr Kulhanek
# -----------------------------------------------------------------------------
# ams-rsync-dpkg - synchronize AMS dpkg

# ------------------------------------------------

if [ -z "$AMS_ROOT_V9" ]; then
    echo "" 1>&2
    echo ">>> ERROR: AMS_ROOT_V9 is not set!" 1>&2
    echo "" 1>&2
    exit 1
fi

# load library functions

source "$AMS_ROOT_V9/share/sync/ams-sync-lib"

# ------------------------------------------------

# we have piped commands and all must succeed
set -o pipefail

# ------------------------------------------------

read_profile_rsync_dpkg

# -----------------------------------------------------------------------------

if [ -z "$AMS_DST_HOST" ]; then
    echo ">>> ERROR: AMS_DST_HOST is not set!" 1>&2
    exit 1
fi
if [ -z "$AMS_DST_DPKGROOT" ]; then
    echo ">>> ERROR: AMS_DST_DPKGROOT is not set!" 1>&2
    exit 1
fi

# ------------------------------------------------------------------------------

AMS_SRC_SOFTMODS="$AMS_ROOT_V9"
AMS_DST_SOFTMODS="$AMS_DST_DPKGROOT/$AMS_ROOT_V9"

# ------------------------------------------------------------------------------

echo ""
create_log_file || exit 1
check_auth      || exit 1
lock_session    || exit 1

if [[ $AMS_DST_HOST != "localhost" ]]; then
    test_password_less_ssh || exit 1
fi

# ------------------------------------------------------------------------------

umask 022

echo "" | tee -a $LOG_FILE
echo "# AMS DPKG - Sync Data" | tee -a $LOG_FILE
echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE

if [[ $AMS_DST_HOST == "localhost" ]]; then
    umask 022
    rm -rf $AMS_DST_DPKGROOT 2> /dev/null
    if [[ ! (-d "$AMS_DST_SOFTMODS") ]]; then
        mkdir -p "$AMS_DST_SOFTMODS" >> $LOG_FILE 2>&1
        if [ $? -ne 0 ]; then exit 1; fi
    fi
    rsync -av $AMS_RSYNC_OPTS --chmod=u+rwX,og+rX,og-w \
          --exclude-from=$AMS_ROOT_V9/share/sync/rsync/exclude/ams-exclude-rules-core \
          "$AMS_SRC_SOFTMODS/" "$AMS_DST_SOFTMODS/" >> $LOG_FILE 2>&1
else
    ssh -x $AMS_DST_HOST \
        "umask 022; rm -rf \"$AMS_DST_DPKGROOT\" if [[ ! (-d \"$AMS_DST_SOFTMODS\") ]]; then mkdir -p \"$AMS_DST_SOFTMODS\" ; fi;" \
        >> $LOG_FILE 2>&1
    if [ $? -ne 0 ]; then exit 1; fi
    rsync -e "ssh -x" -av $AMS_RSYNC_OPTS --chmod=u+rwX,og+rX,og-w \
          --exclude-from=$AMS_ROOT_V9/share/sync/rsync/exclude/ams-exclude-rules-dpkg \
          "$AMS_SRC_SOFTMODS/" "$AMS_DST_HOST:$AMS_DST_SOFTMODS/" >> $LOG_FILE 2>&1
fi

if [ $? -eq 0 ]; then
    echo "  AMS Core Synchronization ... [OK]"
else
    echo "  AMS Core Synchronization ... [FAILED]"
    show_log_error
    exit 1
fi

# ------------------------------------------------------------------------------

# gen new control file
VERSION="`cat \"$AMS_ROOT_V9/var/sync/dpkgver\" 2>/dev/null`"
((VERSION++))
echo "$VERSION" > "$AMS_ROOT_V9/var/sync/dpkgver"

rm -rf "$AMS_ROOT_V9/var/sync/dpkg"
cp -r  "$AMS_ROOT_V9/share/dpkg" "$AMS_ROOT_V9/var/sync/dpkg"

sed -e "s/VERSION/$VERSION/g" < "$AMS_ROOT_V9/var/sync/dpkg/DEBIAN/control.tmp" > "$AMS_ROOT_V9/var/sync/dpkg/DEBIAN/control"

if [[ $AMS_DST_HOST == "localhost" ]]; then
    rsync -e "ssh -x" -av $AMS_RSYNC_OPTS --chmod=u+rwX,og+rX,og-w \
          --exclude-from=$AMS_ROOT_V9/share/sync/rsync/exclude/ams-exclude-rules-ctrl \
          "$AMS_SRC_SOFTMODS/var/sync/dpkg/" "$AMS_DST_DPKGROOT/" >> $LOG_FILE 2>&1
else
    rsync -e "ssh -x" -av $AMS_RSYNC_OPTS --chmod=u+rwX,og+rX,og-w \
          --exclude-from=$AMS_ROOT_V9/share/sync/rsync/exclude/ams-exclude-rules-ctrl \
          "$AMS_SRC_SOFTMODS/var/sync/dpkg/" "$AMS_DST_HOST:$AMS_DST_DPKGROOT/" >> $LOG_FILE 2>&1
fi

if [ $? -eq 0 ]; then
    echo "  AMS DPKG Synchronization ... [OK]"
else
    echo "  AMS DPKG Synchronization ... [FAILED]"
    show_log_error
    exit 1
fi

# ------------------------------------------------------------------------------

echo ""
unlock_session
echo "> Log file: $LOG_FILE"
echo ""

exit 0


