#!/bin/bash

echo "  * Running postinst: $*"
if [ "$1" == "configure" ]; then
    echo "== ncbr-ams-core-personal (postinst):"

    # create infinity user
    echo "   creating infinity user ..."
    adduser --system --user-group --shell /bin/bash --create-home  --home-dir /var/lib/infinity \
            --skel /software/ncbr/softmods/8.0/share/skel

    # change file ownership
    echo "   updating access rights to softmods ..."
    chown -R infinity:infinity /software/ncbr/softmods || exit 1

    # setup softrepo
    echo "   updating access rights to softrepo ..."
    mkdir -m 755 -p /software/ncbr/softrepo || exit 1
    chown infinity:infinity /software/ncbr/softmods || exit 1
fi

exit 0

