#!/bin/bash

echo "  * Running postinst: $*"
if [ "$1" == "configure" ]; then
    echo "== ncbr-ams-core-personal (postinst):"

    # create infinity user
    echo "   creating infinity user ..."
    useradd --system --user-group --shell /bin/bash --create-home --home-dir /var/lib/infinity \
            --skel /software/ncbr/softmods/8.0/share/skel

    # change file ownership
    echo "   creating infinity user ..."
    chown -R infinity:infinity /software/ncbr/softmods || exit 1

    # setup softrepo
    mkdir -p /software/ncbr/softrepo
    chown -R infinity:infinity /software/ncbr/softmods || exit 1
fi

exit 0

