#!/bin/bash

# check number of arguments ----------------------
if [ $# -ne 2 ]; then
  echo "usage: ams-stamp <root> <appdir>"
  exit 1
fi

# list directory ---------------------------------

rm -f /tmp/ams-stamp.$$ &> /dev/null

cd $1
echo $2 | tr '/' '\n' | while read DIR; do
    stat --printf="%n%U%G%a" $DIR >> /tmp/ams-stamp.$$
    cd $DIR
done

cd $1/$2
find . -printf "%p%s%U%G%m%T@%C@" >> /tmp/ams-stamp.$$

md5sum /tmp/ams-stamp.$$ | awk '{print $1}'

rm -f /tmp/ams-stamp.$$ &> /dev/null

