#!/bin/bash
# =============================================================================
# AMS - Advanced Module System
# (c) 2010,2016,2017 Petr Kulhanek
# -----------------------------------------------------------------------------
# ams-rsync-pull - synchronize software repository in pull mode
#
# ams-rsync-pull [action]
#
# actions: rmindx bldlib softrepo

# we have piped commands and all must succeed
set -o pipefail

# -----------------------------------------------------------------------------

if [ -z "$AMS_SYNC_PROFILE" ]; then
    echo ">>> ERROR: AMS_SYNC_PROFILE is not set!" 1>&2
    exit 1
fi
if [ -z "$AMS_DST_HOST" ]; then
    echo ">>> ERROR: AMS_DST_HOST is not set!" 1>&2
    exit 1
fi
if [ -z "$AMS_DST_SOFTMODS" ]; then
    echo ">>> ERROR: AMS_DST_SOFTMODS is not set!" 1>&2
    exit 1
fi
if [ -z "$AMS_DST_SOFTREPO" ]; then
    echo ">>> ERROR: AMS_DST_SOFTREPO is not set!" 1>&2
    exit 1
fi
if [ -z "$AMS_SYNC_SITES" ]; then
    echo ">>> ERROR: AMS_SYNC_SITES is not set!" 1>&2
    exit 1
fi

# ------------------------------------------------------------------------------

# check if AMS_ROOT is set -----------------------

if [ -z "$AMS_ROOT" ]; then
    echo "" 1>&2
    echo ">>> ERROR: AMS_ROOT is not set!" 1>&2
    echo "" 1>&2
    exit 1
fi

# check if SOFTREPO is set -----------------------

if [ -z "$SOFTREPO" ]; then
    echo "" 1>&2
    echo ">>> ERROR: SOFTREPO is not set!" 1>&2
    echo "" 1>&2
    exit 1
fi

umask 027
mkdir -p "$AMS_ROOT/var/sync/$AMS_SYNC_PROFILE/logs"
if [ $? -ne 0 ]; then
    echo "" 1>&2
    echo ">>> ERROR: Unable to create $AMS_ROOT/var/$AMS_SYNC_PROFILE/logs directory!" 1>&2
    echo "" 1>&2
    exit 1
fi

# log file
LOG_FILE="$AMS_ROOT/var/sync/$AMS_SYNC_PROFILE/logs/`date +%Y-%m-%d#%H:%M:%S`.log"

echo ">>> Log file: $LOG_FILE"

# indexes
NEW_INDEX="$AMS_ROOT/var/sync/$AMS_SYNC_PROFILE/index.new"
MST_INDEX="$AMS_ROOT/var/sync/$AMS_SYNC_PROFILE/index.mst"

# -------------------------------------------------------------------------------------

function show_log_error()
{
    echo "" 1>&2
    echo ">>> ERROR: Log file: $LOG_FILE" 1>&2
    echo "    Last 10 lines ..." 1>&2
    tail -10 "$LOG_FILE" | awk '{ printf("    %s\n",$0); }' 1>&2
    echo "" 1>&2
}

# -------------------------------------------------------------------------------------

test_password_less_ssh()
{
    echo -n ">>> Testing connection to: $AMS_SRC_HOST ... " | tee -a $LOG_FILE
    ssh -x -o "BatchMode=yes" -o "StrictHostKeyChecking=no" "$AMS_SRC_HOST" "/bin/echo" >> $LOG_FILE 2>&1
    if [ $? -ne 0 ]; then
        echo "failure" | tee -a $LOG_FILE
        echo "" 1>&2
        echo ">>> ERROR: Passwordless ssh connection with $AMS_SRC_HOST is not available!"  1>&2
        echo "" 1>&2
        show_log_error
        exit 1
    fi
    echo "success" | tee -a $LOG_FILE
}

# -------------------------------------------------------------------------------------

rsync_amscore_cache()
{
    echo "" | tee -a $LOG_FILE
    echo "# AMS core - update site caches" | tee -a $LOG_FILE
    echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE

    umask 022
    echo -n "AMS module cache updated              ... "

    SITES="`echo $AMS_SYNC_SITES | tr ' ' '\n' | awk '{ if( NR > 1 ) printf(","); printf("%s",$1) }'`"
    $AMS_ROOT/bin/ams-cache --sites "$SITES" rebuildall >> $LOG_FILE 2>&1
    if [ $? -eq 0 ]; then
        echo "[OK]"
    else
        echo "[FAILED]"
        show_log_error
        exit 1
    fi

}

# -------------------------------------------------------------------------------------

rsync_bldlib()
{
    echo "" | tee -a $LOG_FILE
    echo "# AMS build library - sync data" | tee -a $LOG_FILE
    echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE

    umask 022
    if ! [ -d "$AMS_DST_SOFTMODS/etc/map" ]; then
        mkdir -p "$AMS_DST_SOFTMODS/etc/map"
        if [ $? -ne 0 ]; then exit 1; fi;
    fi

    echo -n "AMS build library synchronization     ... "

    rsync -e "ssh -x" -av --delete $AMS_RSYNC_OPTS --chmod=u+rwX,og+rX,og-w --exclude-from=$AMS_ROOT/share/sync/rsync/ams-exclude-rules-blds \
         "$AMS_SRC_HOST:$AMS_SRC_SOFTMODS/etc/map/" "$AMS_DST_SOFTMODS/etc/map/" >> $LOG_FILE 2>&1

    if [ $? -eq 0 ]; then
        echo "[OK]"
    else
        echo "[FAILED]"
        show_log_error
        exit 1
    fi
}

# -------------------------------------------------------------------------------------

rsync_amsindex()
{
    echo "" | tee -a $LOG_FILE
    echo "# AMS master index - sync data" | tee -a $LOG_FILE
    echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE

    umask 022

    echo -n "AMS master index synchronization      ... "

    if [ -n "$AMS_MASTER_INDEX" ]; then
        scp "$AMS_SRC_HOST:$AMS_SRC_SOFTMODS/var/sync/$AMS_MASTER_INDEX/index.old" "$MST_INDEX" >> $LOG_FILE 2>&1

        if [ $? -eq 0 ]; then
            echo "[OK]"
        else
            echo "[FAILED]"
            show_log_error
            exit 1
        fi
    fi
}


# -------------------------------------------------------------------------------------

rsync_softrepo()
{
# create new index file
    echo "" | tee -a $LOG_FILE
    echo "# AMS softrepo - generating new repository index" | tee -a $LOG_FILE
    echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE

    SITES="`echo $AMS_SYNC_SITES | tr ' ' '\n' | awk '{ if( NR > 1 ) printf(","); printf("%s",$1) }'`"
    $AMS_ROOT/bin/ams-repoindex-create-ams --personal --sites "$SITES" "$NEW_INDEX" --verbose | tee -a $LOG_FILE
    if [ $? -ne 0 ]; then exit 1; fi;

    echo "# Changed builds ..." | tee -a $LOG_FILE
    $AMS_ROOT/bin/ams-repoindex-diff --skipremoved "$MST_INDEX" "$NEW_INDEX" | tee -a $LOG_FILE
    if [ $? -ne 0 ]; then exit 1; fi;

    NCHANGES="`$AMS_ROOT/bin/ams-repoindex-diff --skipremoved "$MST_INDEX" "$NEW_INDEX" | wc -l`"
    if [ "$NCHANGES" -eq 0 ]; then
        echo "> No changed builds were detected ..."
        return
    fi

# propagate changes
    echo "" | tee -a $LOG_FILE
    echo "# AMS softrepo - sync data" | tee -a $LOG_FILE
    echo "#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" | tee -a $LOG_FILE

    $AMS_ROOT/bin/ams-repoindex-diff --skipremoved "$MST_INDEX" "$NEW_INDEX" | while read STATUS SHA1 BUILD AMS_PACKAGE_DIR; do
        (
        printf "%-60s " "$BUILD"
        echo "==== $BUILD" >> $LOG_FILE

    # get list of root app directories and their setup (permision and group)
        ssh -x $AMS_SRC_HOST "cd $AMS_SRC_SOFTREPO; echo $AMS_PACKAGE_DIR | tr '/' '\n' | while read A; do stat --format=\"%n %G %a\" \$A; cd \$A; done" > /tmp/perms.$$ 2>> $LOG_FILE

    # create app root directory
        BACKUP_PWD=$PWD
        MY_GROUP=`id -g -n $AMS_DST_USER`
        cd "$AMS_DST_SOFTREPO"
        cat /tmp/perms.$$ | while read NAME GROUP PERM; do
            mkdir -p "$NAME"
            chmod "$PERM" "$NAME"
            # ignore GROUP and use group of AMS_DST_USER
            chgrp "$MY_GROUP" "$NAME"
            cd "$NAME"
        done >> $LOG_FILE 2>&1
        cd $BACKUP_PWD
        rm -f /tmp/perms.$$ >> $LOG_FILE 2>&1

    # copy data
        rsync -e "ssh -x" --timeout=50000 -av --delete $AMS_RSYNC_OPTS \
              "$AMS_SRC_HOST:$AMS_SRC_SOFTREPO/$AMS_PACKAGE_DIR/" "$AMS_DST_SOFTREPO/$AMS_PACKAGE_DIR/" >> $LOG_FILE 2>&1
        if [ $? -ne 0 ]; then
            echo "             [FAILED]"
            show_log_error
            exit 1
        else
            echo "             [SYNC]"
        fi
        ) < /dev/null
        if [ $? -ne 0 ]; then exit 1; fi
    done
}

# ==============================================================================
# ------------------------------------------------------------------------------
# ==============================================================================

test_password_less_ssh || exit 1

ACTION="$1"

case "$ACTION" in
    "rmindx")
        rm -f "$NEW_INDEX"
        rm -f "$MST_INDEX"
        if [ $? -ne 0 ]; then exit 1; fi;
        ;;
    "bldlib")
        rsync_bldlib
        if [ $? -ne 0 ]; then exit 1; fi;
        ;;
    "softrepo")
        rsync_amscore_cache
        if [ $? -ne 0 ]; then exit 1; fi;
        rsync_amsindex
        if [ $? -ne 0 ]; then exit 1; fi;
        rsync_softrepo
        if [ $? -ne 0 ]; then exit 1; fi;
        ;;
    *)
        echo "" 1>&2
        echo ">>> ERROR: ACTION '$ACTION' is not supported!" 1>&2
        echo "" 1>&2
    ;;
esac

echo ""
echo "END: Log file is in: $LOG_FILE"
echo ""

exit 0

# -------------------------------------------------------------------------------------
