#!/bin/bash
# ------------------------------------------------------------------------------
# Advanced Module System - personal site management utility
# (c) 2024 Petr Kulhanek
# (c) 2017 Petr Kulhanek
# ------------------------------------------------------------------------------

function initenv_print_header()
{
    echo ""
    echo "#------------------------------------------------------"
    echo "#    *** Shell Environment Startup File Update ***     "
    echo "#------------------------------------------------------"
}

# ------------------------------------------------------------------------------

function initenv_backup_old_files()
{
    echo ""
    echo "1) Backuping old user startup files ..."

    SEQ=`date +"%s"`
    if [ -f ~/.profile ]; then
        mv ~/.profile ~/.profile.$SEQ
        echo "   ~/.profile        -> ~/.profile.$SEQ"
    fi
    if [ -f ~/.bash_profile ]; then
        mv ~/.bash_profile ~/.bash_profile.$SEQ
        echo "   ~/.bash_profile   -> ~/.bash_profile.$SEQ"
    fi
    if [ -f ~/.bashrc ]; then
        mv ~/.bashrc ~/.bashrc.$SEQ
        echo "   ~/.bashrc         -> ~/.bashrc.$SEQ"
    fi
}

# ------------------------------------------------------------------------------

function initenv_create_new_files()
{
    echo ""
    echo "2) Creating new user startup files ..."

cat << EOF > ~/.bash_profile
#--------------------------------------
# Standard NCBR .bash_profile
#--------------------------------------

# include .bashrc if it exists
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
EOF
    echo "   ~/.bash_profile"

cat << EOF > ~/.bashrc
#--------------------------------------
# Standard NCBR .bashrc
#--------------------------------------

# use system wide setup
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
EOF
    echo "   ~/.bashrc"
}

# ------------------------------------------------------------------------------

function initenv_print_bottom()
{
    echo ""
    echo "#---------------------------------------------------------"
    echo "#                  *** End of update ***                  "
    echo "#                                                         "
    echo "# = NEW SESSION MUST BE OPENED (LOGOUT AND LOGIN AGAIN) = "
    echo "#---------------------------------------------------------"
    echo ""
}

# ------------------------------------------------------------------------------

initenv_print_header
initenv_backup_old_files || exit 1
initenv_create_new_files || exit 1
initenv_print_bottom








