#!/bin/bash

AMS_PERS=/software/ncbr/softmods/8.0/share/personal

function print_header()
{
    echo ""
    echo "#------------------------------------------------------"
    echo "# *** Add the current user into the infinity group *** "
    echo "#------------------------------------------------------"

    if [ "`id -u -n`" != "root" ]; then
        echo "" 2>&1
        echo ">>> ERROR: This script must be run by the root user!" 2>&1
        echo "" 2>&1
        echo "    \$ sudo $AMS_PERS/ams-personal-useradd <user>" 2>&1
        echo "" 2>&1
        exit 1
    fi

    if [ -z "$1" ]; then
        echo "" 2>&1
        echo ">>> ERROR: User not specified!" 2>&1
        echo "" 2>&1
        echo "    \$ sudo $AMS_PERS/ams-personal-useradd <user>" 2>&1
        echo "" 2>&1
        exit 1
    fi

    id -- "$1" &> /dev/null
    if [ $? -ne 0 ] ; then
        echo "" 2>&1
        echo ">>> ERROR: User '$1' does not exist!" 2>&1
        echo "" 2>&1
        echo "    \$ sudo $AMS_PERS/ams-personal-useradd <user>" 2>&1
        echo "" 2>&1
        exit 1
    fi
}

# --------------------------------------

function add_user_to_infinity()
{
    echo ""
    echo "# Adding user '$1' into the infinity group ..."
    usermod -a -G infinity -- "$1"
    if [ $? -ne 0 ] ; then
        echo "" 2>&1
        echo ">>> ERROR: Unable to add user '$1' to the infinity group!" 2>&1
        echo "" 2>&1
        exit 1
    fi
}

# --------------------------------------

function print_bottom()
{
    echo ""
    echo "#---------------------------------------------------------"
    echo "#                        *** DONE ***                     "
    echo "#                                                         "
    echo "# = NEW SESSION MUST BE OPENED (LOGOUT AND LOGIN AGAIN) = "
    echo "#---------------------------------------------------------"
    echo ""
}

# --------------------------------------

print_header "$@"
add_user_to_infinity "$@"
print_bottom



