#!/bin/bash
# ------------------------------------------------------------------------------
# Advanced Module System synchronization utility for personal site
# ------------------------------------------------------------------------------

echo "FIXME ..."


