#!/bin/bash
# ------------------------------------------------------------------------------
# Advanced Module System - personal site management utility
# (c) 2024 Petr Kulhanek
# (c) 2017 Petr Kulhanek
# ------------------------------------------------------------------------------

if [ -z "$AMS_PERSONAL_ROOT" ]; then
    echo "" 1>&2
    echo ">>> ERROR: AMS_PERSONAL_ROOT is not set!" 1>&2
    echo "" 1>&2
    exit 1
fi

# ------------------------------------------------------------------------------

function print_usage()
{
    echo ""
    echo "Usage: ams-personal [-h][--help] <action> [ARGS]"
    echo ""
    echo "Supported actions for administrator (sudo user):"
    echo "  Management of software modules:"
    echo "    install <module1> [module2 ...] install modules/builds specified by"
    echo "                                      * module name"
    echo "                                      * full build name"
    echo "                                      * build filter (filter is incomplete buildname with wildcard characters)"
    echo "                                      and update all installed builds"
    echo "    remove <module1> [module2 ...]  remove builds specified by full build name or build filter"
    echo "    update                          update all installed builds"
    echo "    upgrade                         upgrade all installed modules"
    echo ""
    echo "  Personal site setup:"
    echo "    gensshkeys         setup sshkeys for the local infinity user"
    echo "    showsshkey         show the public key of the local infinity user"
    echo "    useradd [user]     add 'user' to the infnity group, if not provided the current user is added"
    echo "    envinit            initialize bash startup files for the current user"
    echo "    amsdpkg            install and/or upgrade AMS core packages"
    echo "    coremods           install and/or upgrade AMS core software modules"
    echo "    dpkgdeps           install dependent system packages (called by install/update/upgrade)"
    echo ""
}

# ------------------------------------------------------------------------------

function exec_dpkgdeps() {
    echo ""
    echo "# Installing system dependent packages:"
    echo "# ------------------------------------------------------------------------------"
    echo "# `lsb_release -d`"
    RELEASE=`lsb_release -r | awk '{ print $2; }'`
    PKGS="`amsmodule dpkg-deps 2>&1`"
    if [ $? -ne 0 ]; then
        exit 1
    fi
    if [ -n "$PKGS" ]; then
        for PACK in $PKGS; do
            echo ""
            echo ">> $PACK"
            # ignore errors; some packages might be unavailable, thus install per partes
            sudo apt-get --assume-yes install $PACK
        done
    else
        echo "  No dependencies ..."
    fi
    echo ""
}

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------

SHIFT="-"
while [ -n "$SHIFT" ]; do
    SHIFT=""
    case $1 in
        '-h'|'--help')
            print_usage
            exit 0
        ;;
    esac
done

# -----------------------------------------------------------------------------------------

if [ "`id -g -n`" == "infinity" ] || [ "`id -u -n`" == "root" ]; then
    echo "" 1>&2
    echo ">>> ERROR: The ams-personal command cannot be run by 'infinity' or 'root' users!" 1>&2
    echo "" 1>&2
    exit 1
fi

if [ $# -lt 1 ]; then
    echo "" 1>&2
    echo ">>> ERROR: Incorrect number of arguments!" 1>&2
    print_usage
    exit 1
fi

# -----------------------------------------------------------------------------------------

ACTION="$1"
shift

# this action does not require full Infinity activation

case "$ACTION" in
# -----------------------------
    "useradd" )
        AUSER="$2"
        if [ -z "$AUSER" ]; then
            AUSER="`whoami`"
        fi
        sudo $AMS_PERSONAL_ROOT/share/personal/ams-personal-useradd "$AUSER" || exit 1
        exit 0
        ;;
esac

# -----------------------------------------------------------------------------------------

id -G -n 2> /dev/null | grep "infinity" &> /dev/null
if [ $? -ne 0 ]; then
    echo "" 1>&2
    echo ">>> ERROR: This action requires that you are a member of the infinity group!" 1>&2
    echo "" 1>&2
    echo "           Run the following command to fix the problem:" 1>&2
    echo "           $ ams-personal useradd" 1>&2
    echo "" 1>&2
    exit 1
fi

# this action does not require full Infinity activation

case "$ACTION" in
# -----------------------------
    "envinit" )
        $AMS_PERSONAL_ROOT/share/personal/ams-personal-envinit || exit 1
        exit 0
        ;;
esac

# -----------------------------------------------------------------------------------------

# check if AMS_ROOT_V9 is set -----------------------

if [ -z "$AMS_ROOT_V9" ]; then
    echo "" 1>&2
    echo ">>> ERROR: AMS_ROOT_V9 is not set!" 1>&2
    echo "           You need to modify your startup files by running the command:" 1>&2
    echo "" 1>&2
    echo "           $ ams-personal envinit" 1>&2
    echo "" 1>&2
    exit 1
fi

id -G -n 2> /dev/null | grep "sudo" &> /dev/null
if [ $? -ne 0 ]; then
    echo "" 1>&2
    echo ">>> ERROR: This action can be performed by the administrator only (the \"sudo\" user)!" 1>&2
    echo "" 1>&2
    exit 1
fi

case "$ACTION" in
# -----------------------------
    "install" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-install "$@" || exit 1
        exec_dpkgdeps
        ;;
# -----------------------------
    "coremods" )
        echo ""
        echo "# Installing/upgrading AMS core modules:"
        echo "# ------------------------------------------------------------------------------"
        LIST="`site listamods personal 2>&1`"
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-install $LIST || exit 1
        exec_dpkgdeps
        ;;
# -----------------------------
    "update" )
        echo ""
        echo "# Updating AMS builds:"
        echo "# ------------------------------------------------------------------------------"
        LIST="`amsmodule allbuilds 2>&1`"
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-install $LIST || exit 1
        exec_dpkgdeps
        ;;
# -----------------------------
    "upgrade" )
        echo ""
        echo "# Upgrading AMS modules:"
        echo "# ------------------------------------------------------------------------------"
        LIST="`amsmodule allmodules 2>&1`"
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-install $LIST || exit 1
        exec_dpkgdeps
        ;;
# -----------------------------
    "remove" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-remove "$@"
        ;;
# -----------------------------
    "amsdpkg" )
        echo ""
        echo "# Installing/upgrading AMS core packages:"
        echo "# ------------------------------------------------------------------------------"
        PKGS="ncbr-ams-core-9.0-personal"
        if [ $? -ne 0 ]; then
            exit 1
        fi
        sudo apt-get update
        sudo apt-get install $PKGS || exit 1
        echo ""
        ;;
# -----------------------------
    "dpkgdeps" )
        exec_dpkgdeps || exit 1
        ;;
# -----------------------------
    "gensshkeys" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-gensshkeys "$@"
        ;;
# -----------------------------
    "showsshkey" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-showsshkey "$@"
        ;;
# -----------------------------
    *)
        echo "" 1>&2
        echo ">>> ERROR: Unsupported action!" 1>&2
        print_usage
        exit 1
        ;;
esac
