#!/bin/bash
# ------------------------------------------------------------------------------
# Advanced Module System - personal site management utility
# (c) 2017 Petr Kulhanek
# ------------------------------------------------------------------------------

if [ -z "AMS_PERSONAL_ROOT" ]; then
    echo "" 1>&2
    echo ">>> ERROR: AMS_PERSONAL_ROOT is not set!" 1>&2
    echo "" 1>&2
fi

# ------------------------------------------------------------------------------

function print_usage()
{
    echo ""
    echo "Usage: ams-personal [-h][--help] <action> [ARGS]"
    echo ""
    echo "Supported actions for administrator (sudo user):"
    echo "   Management of module builds:"
    echo "       addmodules <module1> ...            install modules (only single modes)"
    echo "                                              and update all local builds"
    echo "       addbuilds <[prefix]/bldfilter1> ... install builds specified by full build name or build filter"
    echo "                                              (filter is incomplete buildname with wildcard characters)"
    echo "                                              and update all local builds"
    echo "       rmbuilds <bldfilter1> ...           remove builds specified by full build name or build filter"
    echo "       update                              update all local builds"
    echo "       upgrade                             upgrade modules to the most recent builds (by verindx, only single modes)"
    echo "                                              and update all local builds"
    echo "       debdeps                             install dependent system packages"
    echo ""
    echo "   Personal site setup:"
    echo "       gensshkeys         setup sshkeys for the local infinity user"
    echo "       showsshkey         show the public key of the local infinity user"
    echo "       useradd [user]     add 'user' to the infnity group, if not provided the current user is added"
    echo "       envinit            initialize bash startup files for the current user"
    echo "       addcorebuilds      install AMS core builds"
    echo "       amscore            upgrade AMS core packages"
    echo ""
    echo "Supported actions for ordinary user:"
    echo "   Personal site setup:"
    echo "       initenv            initialize bash startup files for the current user"
    echo ""
    echo "General pre-requisites for a computer:"
    echo "       * ncbr-ams-core-X.Y-personal package must by installed"
    echo "       * passwordless connection to the infinity softrepo must be configured (use 'sshkeys')"
    echo ""
    echo "General pre-requisites for a user employing the infinity environment:"
    echo "       * the user must be a member of the infinity group (use 'useradd')"
    echo "       * the user must have correct bash startup files (use 'envinit')"
    echo ""

}

# ------------------------------------------------------------------------------

function exec_debdeps() {
    sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal bldlib || exit 1
    echo ""
    echo "# Installing system dependent packages:"
    echo "# ------------------------------------------------------------------------------"
    PKGS="`ams-cache debdepsall`"
    if [ $? -ne 0 ]; then
        exit 1
    fi
    sudo apt-get install $PKGS  || exit 1
    echo ""
}

# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------

SHIFT="-"
while [ -n "$SHIFT" ]; do
    SHIFT=""
    case $1 in
        '-h'|'--help')
            print_usage
            exit 0
        ;;
    esac
done

# -----------------------------------------------------------------------------------------

if [ "`id -g -n`" == "infinity" ] || [ "`id -u -n`" == "root" ]; then
    echo "" 1>&2
    echo ">>> ERROR: The ams-personal command cannot be run by 'infinity' or 'root' users!" 1>&2
    echo "" 1>&2
    exit 1
fi

if [ $# -lt 1 ]; then
    echo "" 1>&2
    echo ">>> ERROR: Incorrect number of arguments!" 1>&2
    print_usage
    exit 1
fi

# -----------------------------------------------------------------------------------------

ACTION="$1"
shift

# this action does not require full Infinity activation

case "$ACTION" in
# -----------------------------
    "useradd" )
        AUSER="$2"
        if [ -z "$AUSER" ]; then
            AUSER="`whoami`"
        fi
        sudo $AMS_PERSONAL_ROOT/share/personal/ams-personal-useradd "$AUSER" || exit 1
        exit 0
        ;;
esac

# -----------------------------------------------------------------------------------------

id -G -n 2> /dev/null | grep "infinity" &> /dev/null
if [ $? -ne 0 ]; then
    echo "" 1>&2
    echo ">>> ERROR: This action requires that you are a member of the infinity group!" 1>&2
    echo "" 1>&2
    echo "           Run the following command to fix the problem:" 1>&2
    echo "           $ ams-personal useradd" 1>&2
    echo "" 1>&2
    exit 1
fi

# this action does not require full Infinity activation

case "$ACTION" in
# -----------------------------
    "envinit" )
        $AMS_PERSONAL_ROOT/share/personal/ams-personal-envinit || exit 1
        exit 0
        ;;
esac

# -----------------------------------------------------------------------------------------

# check if AMS_ROOT is set -----------------------

if [ -z "$AMS_ROOT" ]; then
    echo "" 1>&2
    echo ">>> ERROR: AMS_ROOT is not set!" 1>&2
    echo "           You need to modify your startup files by running the command:" 1>&2
    echo "" 1>&2
    echo "           $ ams-personal initenv" 1>&2
    echo "" 1>&2
    exit 1
fi

id -G -n 2> /dev/null | grep "sudo" &> /dev/null
if [ $? -ne 0 ]; then
    echo "" 1>&2
    echo ">>> ERROR: This action can be performed by the administrator only (the \"sudo\" user)!" 1>&2
    echo "" 1>&2
    exit 1
fi

case "$ACTION" in
# -----------------------------
    "addmodules" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal bldlib || exit 1
        echo ""
        echo "# AMS modules for sites: `site listavail 2>&1 | awk '{ if(i>0) printf(","); printf("%s",$1); i++;}' `"
        echo "# ------------------------------------------------------------------------------"
        CORE_BUILDS=""
        for SITE in `site listavail 2>&1`; do
            for MOD in "$@"; do
                CORE_BUILDS="$CORE_BUILDS `ams-map-manip bestbuild $SITE $MOD`"
            done
        done
        CORE_BUILDS="`echo $CORE_BUILDS | tr " " "\n" | sort -u`"
        echo $CORE_BUILDS | tr " " "\n"

        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS || exit 1
        exec_debdeps || exit 1
        ;;
# -----------------------------
    "addbuilds" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-addbuilds "$@" || exit 1
        exec_debdeps || exit 1
        ;;
# -----------------------------
    "addcorebuilds" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal bldlib  || exit 1
        echo ""
        echo "# AMS core builds for sites: `site listavail 2>&1 | awk '{ if(i>0) printf(","); printf("%s",$1); i++;}' `"
        echo "# ------------------------------------------------------------------------------"
        CORE_BUILDS=""
        for SITE in `site listavail 2>&1`; do
            for MOD in `site listamods $SITE 2>&1`; do
                CORE_BUILDS="$CORE_BUILDS `ams-map-manip bestbuild $SITE $MOD`"
            done
        done
        CORE_BUILDS="`echo $CORE_BUILDS | tr " " "\n" | sort -u`"
        echo $CORE_BUILDS | tr " " "\n"

        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS || exit 1
        exec_debdeps || exit 1
        ;;
# -----------------------------
    "update" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal bldlib || exit 1
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal softrepo || exit 1
        exec_debdeps || exit 1
        ;;
# -----------------------------
    "upgrade" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/scripts/ams-sync personal bldlib || exit 1
        echo ""
        echo "# AMS best builds for sites: `site listavail 2>&1 | awk '{ if(i>0) printf(","); printf("%s",$1); i++;}' `"
        echo "# ------------------------------------------------------------------------------"
        CORE_BUILDS=""
        for SITE in `site listavail 2>&1`; do
            for MOD in `ams-cache --site $SITE allmods`; do
                CORE_BUILDS="$CORE_BUILDS `ams-map-manip upgradebuild $SITE $MOD`"
            done
        done
        CORE_BUILDS="`echo $CORE_BUILDS | tr " " "\n" | sort -u`"
        echo $CORE_BUILDS | tr " " "\n"

        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-addbuilds $CORE_BUILDS || exit 1
        exec_debdeps || exit 1
        ;;
# -----------------------------
    "rmbuilds" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-rmbuilds "$@"
        ;;
# -----------------------------
    "amscore" )
        echo ""
        echo "# Installing/upgrading AMS core packages:"
        echo "# ------------------------------------------------------------------------------"
        PKGS="ncbr-ams-core-8.0-personal ncbr-env-infinity-8.0-personal"
        if [ $? -ne 0 ]; then
            exit 1
        fi
        sudo apt-get update
        sudo apt-get install $PKGS || exit 1
        echo ""
        ;;
# -----------------------------
    "debdeps" )
        exec_debdeps || exit 1
        ;;
# -----------------------------
    "gensshkeys" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-gensshkeys "$@"
        ;;
# -----------------------------
    "showsshkey" )
        sudo -u infinity -i $AMS_PERSONAL_ROOT/share/personal/ams-personal-showsshkey "$@"
        ;;
# -----------------------------
    *)
        echo "" 1>&2
        echo ">>> ERROR: Unsupported action!" 1>&2
        print_usage
        exit 1
        ;;
esac







