#!/bin/bash
# ------------------------------------------------------------------------------
# Advanced Module System - personal site management utility
# (c) 2024 Petr Kulhanek
# (c) 2017 Petr Kulhanek
# ------------------------------------------------------------------------------

function print_bottom()
{
    echo "Public Infinity ssh key:"
    cat "/var/lib/infinity/.ssh/id_rsa.pub"
    echo ""
}

# --------------------------------------

print_bottom



