#!/bin/bash
# ------------------------------------------------------------------------------
# Advanced Module System - personal site management utility
# (c) 2024 Petr Kulhanek
# (c) 2017 Petr Kulhanek
# ------------------------------------------------------------------------------

function print_bottom()
{
    echo "Public Infinity ssh key:"
    if [ -f /var/lib/infinity/.ssh/id_rsa.pub ]; then
        cat "/var/lib/infinity/.ssh/id_rsa.pub"
    else
        echo ">>> ERROR: File with the ssh key '/var/lib/infinity/.ssh/id_rsa.pub' does not exist!" 1>&2
        echo "           You can generate the key by running the command:" 1>&2
        echo "" 1>&2
        echo "           $ ams-personal gensshkeys" 1>&2
        echo "" 1>&2
    fi
    echo ""
}

# --------------------------------------

print_bottom



