#!/bin/bash

function print_header()
{
    echo ""
    echo "#------------------------------------------------------"
    echo "#  *** Initialize ssh-keys for the infinity user ***   "
    echo "#------------------------------------------------------"

    if [ "`id -u -n`" != "infinity" ]; then
        echo "" 2>&1
        echo ">>> ERROR: This script must be run by the infinity user!" 2>&1
        echo "" 2>&1
        echo "    \$ sudo -u infinity -i ams-personal-sshkeys" 2>&1
        echo "" 2>&1
        exit 1
    fi

    echo ""
    echo "This will invalidate the previous ssh kyes of the infnity user."
    echo -n "Do you want to continue? (YES/NO) "
    read CONF
    if [ "$CONF" != "YES" ]; then
        echo "Execution interrupted!" 2>&1
        exit 1
    fi
}

# --------------------------------------

function gen_keys()
{
    echo ""
    echo "# Generating ssh keys ...."
    rm -f /var/lib/infinity/.ssh/id_rsa /var/lib/infinity/.ssh/id_rsa.pub
    ssh-keygen -N "" -f /var/lib/infinity/.ssh/id_rsa
}

# --------------------------------------

function print_bottom()
{
    echo ""
    echo "#---------------------------------------------------------"
    echo "#             *** End of ssh keys update ***              "
    echo "#---------------------------------------------------------"
    echo ""
    echo "Public ssh key:"
    cat "/var/lib/infinity/.ssh/id_rsa.pub"
    echo ""
}

# --------------------------------------

print_header
gen_keys
print_bottom



