#!/bin/bash
# ==============================================================================
# Infinity
# (c) 2017, Petr Kulhanek, kulhanek@chemi.muni.cz
# ==============================================================================

# do we have AMS_ROOT?
if [ -z "$AMS_ROOT" ]; then return 0; fi

# init AMS core
. $AMS_ROOT/etc/boot/init.ams

# reactivate modules
amsmodule reactivate &> /dev/null

return 0



